env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    BUILD_HOSTNAME: "cirrus-ci.org"

task:
  name: HimanishM25
  timeout_in: 4h
  persistent_worker:
    labels:
      name: AX61-2
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 24
        memory: 120G
        volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
          
    clone_repo_script:
      - pwd
      - git clone https://github.com/HimanishM25/ci-build ~/BobTheBuilder
      - chmod -R +x ~/BobTheBuilder
    sync_script:
      - cd ~/BobTheBuilder && ./sync_source
    download_ccache_script:
      - cd ~/BobTheBuilder && ./download_ccache
    tmate_script:
      - cd ~/BobTheBuilder && ./tmate
    # rom_script:
    #   - cd ~/BobTheBuilder && ./build_rom
    # upload_ccache_script:
    #   - cd ~/BobTheBuilder && ./upload_ccache
