#!/bin/bash
cd /tmp/rom
CODENAME=laurel_sprout
OUTDIR=out/target/product/$CODENAME
# Normal build steps
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z
./rom-build.sh laurel_sprout
# Bot Setup
export BOT_MSG_URL="https://api.telegram.org/bot$API_BOT/sendMessage"
export BOT_BUILD_URL="https://api.telegram.org/bot$API_BOT/sendDocument"
TG_USERNAME=@k_fene_8

send_msg() {
        curl -s -X POST "$BOT_MSG_URL" -d chat_id="$2" \
                -d "parse_mode=html" \
                -d text="$1"
}

send_file() {
        curl -F chat_id=$CHAT_ID -F document=@${1} -F parse_mode=markdown $BOT_BUILD_URL
}

# First builds for testing and to capture ccache
timeout -k 10 90m mka bacon -j$(nproc --all)
