#!/bin/bash
MANIFEST=https://github.com/AOSPA/manifest.git
BRANCH=sapphire
CODENAME=laurel_sprout
BRAND=xiaomi
DT_LINK=https://github.com/HimanishM25/aospa_device_laurel_sprout.git
VT_LINK=https://github.com/HimanishM25/aospa_vendor_xiaomi_laurel_sprout.git
KT_LINK=https://github.com/HimanishM25/aospa_kernel_msm-4.14.git

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "Hemant Sachdeva"
git config --global user.email "hemant.evolver@gmail.com"

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# Clone
git clone $DT_LINK --single-branch -b elle --depth=1 device/$BRAND/$CODENAME
git clone $VT_LINK --single-branch -b elle --depth=1 vendor/$BRAND/$CODENAME
git clone $KT_LINK --single-branch -b elle --depth=1 kernel/msm-4.14
git clone https://github.com/HemantSachdeva/proton-clang --depth=1 prebuilts/clang/host/linux-x86/clang-proton
